export const Phase3ErrorMessages = {
  "01": "name should be a valid value",
  "02": "baseURI should be a valid value",
  "03": "provenance should be a valid value",
  "04": "maxSupply should be greater than 0",
  "05": "pricePerToken should be greater than 0",
  "06": "maxTokensPerWallet should be between 1 and `maxSupply_`",
  "07": "maxTokensPerTxn should be between 1 and `maxSupply_`",
  "08": "invalid roles and/or roleAddresses",
  "09": "no roles",
  "10": "invalid role",
  "11": "invalid totalRoyalty",
  "12": "totalRoyalty should be less than 10000 basis points (100%)",
  "13": "invalid signature",
  "14": "the sale is revealed already",
  "15": "the sale is not active",
  "16": "contract addresses cannot mint tokens",
  "17": "this transaction will exceed the maxSupply",
  "18": "this transaction will exceed the maxTokensPerTxn",
  "19": "this transaction will exceed the maxTokensPerWallet",
  "20": "invalid tokenCount",
  "21": "invalid pricePayoutWallet address",
  "22": "invalid value",
  "23": "tokenId does not exist",
  "24": "balance is 0",
  "25": "newPrice cannot be the same as the current pricePerToken",
  "26": "tokenId provided must be between 0 and maxSupply",
  "27": "Nonce already used",
  "28": "Incorrect number of approvals",
  "29": "Failed verification",
  "30": "Multisig roles and thresholds length mismatch",
  "31": "Duplicate approvals",
  "32": "Invalid signature",
  "33": "Invalid number of tokenIds",
  "34": "This token cannot be transferred",
  "35": "Invalid voucher time window",
};
